

apiVersion: apps/v1
kind: Deployment
metadata:
name: my-nginx
spec:
selector:
matchLabels:
run: my-nginx
replicas: 2
template:
metadata:
labels:
run: my-nginx
spec:
securityContext:
  runAsNonRoot: true
  runAsUser: 0
  allowPrivilegeEscalation: false
containers:
- name: my-nginx
image: nginx
resources:
  requests:
    cpu: 100m
    memory: "512Mi"
ports:
- containerPort: 80